# Generated by Django 4.2.2 on 2023-07-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_comentario_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('-fecha',)},
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
