# Generated by Django 4.2.2 on 2023-07-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_noticia_options_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='noticias.comentario'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria_noticia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='noticias.categoria'),
        ),
    ]
