# Generated by Django 4.2.2 on 2023-07-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_comentario_parent_alter_noticia_categoria_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='parent',
        ),
    ]
