# Generated by Django 4.2.2 on 2023-07-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0009_alter_comentario_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='slug',
            field=models.SlugField(default=True, max_length=510),
            preserve_default=False,
        ),
    ]
