# Generated by Django 4.2.2 on 2023-07-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0010_comentario_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={},
        ),
    ]
