# Generated by Django 4.2.2 on 2023-07-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_alter_noticia_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
