# Generated by Django 4.2.3 on 2023-07-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_user_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='usuarios/user-default.png', null=True, upload_to='usuarios'),
        ),
    ]
