# Generated by Django 4.2.3 on 2023-07-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='static/user-default.jpg', null=True, upload_to='usuarios'),
        ),
    ]
