# Generated by Django 4.2.2 on 2023-07-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('delete_comentario', 'Eliminar comentario'), ('change_comentario', 'Editar comentario'))},
        ),
    ]
